add Collector.Default
c-cube/ocaml-trace pull request #12
Opened 2023-08-29 19:23 UTC by c-cube

- add `add_data_to_span` and `add_data_to_explicit_span`
- update test
- add Collector.Default

2023-08-29 23:34 UTC, ELLIOTTCABLE requested changes

2023-08-29 23:34 UTC, ELLIOTTCABLE commented on src/core/collector.ml
> +
See [my review](https://github.com/c-cube/ocaml-trace/pull/11#pullrequestreview-1601545377) of #11

2023-08-29 23:34 UTC, ELLIOTTCABLE commented on src/core/collector.ml
> +    failwith (Printf.sprintf "not implemented: Trace.Collector.%s" what)
Perhaps it's a good idea to mirror my implementation, and require collectors expose a string-ish `name` that can be printed in debugging contexts like this one?

https://github.com/ELLIOTTCABLE/ocaml-ambient-context/blob/30073325fe8d168ce44ac06b8b338d5b4875b02c/lib/types.ml

2023-08-29 23:34 UTC, ELLIOTTCABLE commented on src/core/collector.ml
> +    failwith (Printf.sprintf "not implemented: Trace.Collector.%s" what)
In fact, perhaps this should even be abstracted — in additional to `message`, add `internal_message`, which `ocaml-trace` itself will call in erroneous situations? This allows collectors to self-collect.

2023-09-17 17:55 UTC, closed without merging

2023-09-17 17:55 UTC, c-cube commented
Guess it's not worth it. Collectors will just have to depend on a more specific version of ocaml-trace.